# Generated by Django 4.0.5 on 2022-07-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем внебюджетных инвестиций или собственных средств'),
        ),
    ]
