# Generated by Django 4.0.5 on 2022-07-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_alter_author_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnumber',
            name='number',
            field=models.CharField(max_length=2, unique=True, verbose_name='Номер секции'),
        ),
    ]
