# Generated by Django 4.0.5 on 2022-07-10 17:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_alter_author_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=12, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='scientificdirector',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=12, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='cont_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона контактного лица', max_length=12, region=None, verbose_name='Телефон'),
        ),
    ]
