# Generated by Django 4.0.5 on 2022-07-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0009_thesisall'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thesisall',
            table='all_thesis',
        ),
    ]
