# Generated by Django 4.0.5 on 2022-07-16 20:06

from django.db import migrations, models
import phonenumber_field.modelfields
import user_data.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0010_alter_thesisall_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(help_text='Пример: mail@hse.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Пример: +79160003333', max_length=12, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='file1',
            field=models.FileField(upload_to='files/', validators=[user_data.validators.validate_file1_extension], verbose_name='Файл с тезисами'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='file2',
            field=models.FileField(upload_to='files/', validators=[user_data.validators.validate_file2_extension], verbose_name='Файл с подписью научного руководителя'),
        ),
    ]
