# Generated by Django 4.0.5 on 2022-07-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0011_alter_author_email_alter_author_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='code',
            field=models.CharField(default='', help_text='12.33.21, 33.23.11', max_length=50, verbose_name='Код рубрики'),
        ),
    ]
