# Generated by Django 4.0.5 on 2022-07-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0012_alter_thesis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='code',
            field=models.CharField(help_text='12.33.21, 33.23.11', max_length=50, verbose_name='Код рубрики'),
        ),
    ]
