# Generated by Django 4.0.5 on 2022-07-16 23:16

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0013_alter_thesis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='faculty',
            field=models.TextField(help_text='МИЭМ НИУ ВШЭ', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='author',
            name='fio',
            field=models.CharField(help_text='Пример: Иванов Сергей Михайлович', max_length=150, verbose_name='ФИО полностью'),
        ),
        migrations.AlterField(
            model_name='author',
            name='fio_short',
            field=models.CharField(help_text='Пример: Иванов С.М.', max_length=100, verbose_name='ФИО фамилия, инициалы'),
        ),
        migrations.AlterField(
            model_name='author',
            name='organization',
            field=models.TextField(help_text='НИУ ВШЭ', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.TextField(help_text='Пример: бакалавр 3 курс', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='author',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='user_data.thesis', verbose_name='Тезис'),
        ),
        migrations.AlterField(
            model_name='scientificdirector',
            name='email',
            field=models.EmailField(help_text='Пример: mail@hse.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='scientificdirector',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Пример: +79160003333', max_length=12, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='code',
            field=models.CharField(help_text='Пример: 12.33.21, 33.23.11', max_length=50, verbose_name='Код рубрики'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='cont_email',
            field=models.EmailField(help_text='Пример: mail@hse.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='cont_fio',
            field=models.CharField(help_text='Пример: Иванов Сергей Михайлович', max_length=150, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='cont_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Пример: +79160003333', max_length=12, region=None, verbose_name='Телефон'),
        ),
    ]
