# Generated by Django 3.2.9 on 2022-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0015_alter_scientificdirector_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='faculty',
            field=models.TextField(help_text='Пример: МИЭМ НИУ ВШЭ', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='author',
            name='organization',
            field=models.TextField(help_text='Пример: НИУ ВШЭ', verbose_name='Организация'),
        ),
    ]
